
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 25 2019 09:55:16 IST (Nov 25 2019 04:25:16 UTC)

// Verification Directory fv/Vedic_8B 

module ha(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_1(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha z1(n_10, n_9, c[1], temp);
  ha_1 z2(temp, n_8, c[2], c[3]);
  AND2XL g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_2(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_3(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_1(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_2 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_3 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_4(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_5(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_2(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_4 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_5 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_6(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_7(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_3(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_6 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_7 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module fourba(x, y, sum);
  input [3:0] x, y;
  output [3:0] sum;
  wire [3:0] x, y;
  wire [3:0] sum;
  wire n_0, n_1, n_3, n_5, n_6, n_7, n_9;
  OAI21XL g94(.A0 (n_7), .A1 (x[3]), .B0 (n_9), .Y (sum[3]));
  NAND2XL g95(.A (x[3]), .B (n_7), .Y (n_9));
  OAI21XL g96(.A0 (n_5), .A1 (x[2]), .B0 (n_6), .Y (sum[2]));
  NAND2BXL g97(.AN (n_5), .B (x[2]), .Y (n_7));
  NAND2XL g98(.A (x[2]), .B (n_5), .Y (n_6));
  AOI22XL g99(.A0 (n_3), .A1 (n_1), .B0 (y[1]), .B1 (x[1]), .Y (n_5));
  MXI2XL g100(.A (n_0), .B (n_3), .S0 (n_1), .Y (sum[1]));
  CLKINVX1 g101(.A (n_0), .Y (n_3));
  CLKXOR2X1 g102(.A (x[0]), .B (y[0]), .Y (sum[0]));
  CLKXOR2X1 g103(.A (x[1]), .B (y[1]), .Y (n_1));
  NAND2XL g104(.A (x[0]), .B (y[0]), .Y (n_0));
endmodule

module sixba(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_1, n_2, n_4, n_6, n_7, n_8, n_10;
  OAI21XL g114(.A0 (n_8), .A1 (y[5]), .B0 (n_10), .Y (sum[5]));
  NAND2XL g115(.A (y[5]), .B (n_8), .Y (n_10));
  OAI21XL g116(.A0 (n_6), .A1 (y[4]), .B0 (n_7), .Y (sum[4]));
  NAND2BXL g117(.AN (n_6), .B (y[4]), .Y (n_8));
  NAND2XL g118(.A (y[4]), .B (n_6), .Y (n_7));
  AOI22XL g119(.A0 (n_4), .A1 (n_2), .B0 (x[3]), .B1 (y[3]), .Y (n_6));
  MXI2XL g120(.A (n_1), .B (n_4), .S0 (n_2), .Y (sum[3]));
  CLKINVX1 g121(.A (n_1), .Y (n_4));
  CLKXOR2X1 g122(.A (y[2]), .B (x[2]), .Y (sum[2]));
  CLKXOR2X1 g123(.A (y[3]), .B (x[3]), .Y (n_2));
  NAND2XL g124(.A (y[2]), .B (x[2]), .Y (n_1));
endmodule

module sixba_1(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_0, n_2, n_3, n_4, n_5, n_7, n_8, n_10;
  wire n_11, n_13, n_14, n_15, n_17;
  OAI21XL g186(.A0 (n_15), .A1 (y[5]), .B0 (n_17), .Y (sum[5]));
  NAND2XL g187(.A (y[5]), .B (n_15), .Y (n_17));
  OAI21XL g188(.A0 (n_13), .A1 (y[4]), .B0 (n_14), .Y (sum[4]));
  NAND2BXL g189(.AN (n_13), .B (y[4]), .Y (n_15));
  NAND2XL g190(.A (y[4]), .B (n_13), .Y (n_14));
  AOI22XL g191(.A0 (n_11), .A1 (n_3), .B0 (x[3]), .B1 (y[3]), .Y
       (n_13));
  MXI2XL g192(.A (n_10), .B (n_11), .S0 (n_3), .Y (sum[3]));
  CLKINVX1 g193(.A (n_10), .Y (n_11));
  AOI22XL g194(.A0 (n_4), .A1 (n_8), .B0 (x[2]), .B1 (y[2]), .Y (n_10));
  MXI2XL g195(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[2]));
  CLKINVX1 g196(.A (n_7), .Y (n_8));
  AOI22XL g197(.A0 (n_2), .A1 (n_5), .B0 (x[1]), .B1 (y[1]), .Y (n_7));
  MXI2XL g198(.A (n_0), .B (n_5), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g199(.A (n_0), .Y (n_5));
  CLKXOR2X1 g200(.A (y[2]), .B (x[2]), .Y (n_4));
  CLKXOR2X1 g201(.A (y[3]), .B (x[3]), .Y (n_3));
  CLKXOR2X1 g202(.A (y[0]), .B (x[0]), .Y (sum[0]));
  CLKXOR2X1 g203(.A (y[1]), .B (x[1]), .Y (n_2));
  NAND2XL g204(.A (y[0]), .B (x[0]), .Y (n_0));
endmodule

module vedic_4_x_4(a, b, c);
  input [3:0] a, b;
  output [7:0] c;
  wire [3:0] a, b;
  wire [7:0] c;
  wire [3:0] q0;
  wire [3:0] q1;
  wire [3:0] q2;
  wire [3:0] q3;
  wire [3:0] q4;
  wire [5:0] q5;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4;
  wire UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z8;
  vedic_2_x_2 z1(a[1:0], b[1:0], {q0[3:2], c[1:0]});
  vedic_2_x_2_1 z2(a[3:2], b[1:0], q1);
  vedic_2_x_2_2 z3(a[1:0], b[3:2], q2);
  vedic_2_x_2_3 z4(a[3:2], b[3:2], q3);
  fourba z5(q1, {UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z, q0[3:2]}, q4);
  sixba z6({UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3, q2[3:2],
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1}, {q3,
       UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z5}, {q5[5:2],
       UNCONNECTED0, UNCONNECTED});
  sixba_1 z7({UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7, q4}, {q5[5:2],
       q2[1:0]}, c[7:2]);
endmodule

module ha_8(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_9(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_4(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_8 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_9 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_10(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_11(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_5(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_10 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_11 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_12(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_13(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_6(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_12 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_13 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_14(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_15(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_7(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_14 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_15 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module fourba_1(x, y, sum);
  input [3:0] x, y;
  output [3:0] sum;
  wire [3:0] x, y;
  wire [3:0] sum;
  wire n_0, n_1, n_3, n_5, n_6, n_7, n_9;
  OAI21XL g94(.A0 (n_7), .A1 (x[3]), .B0 (n_9), .Y (sum[3]));
  NAND2XL g95(.A (x[3]), .B (n_7), .Y (n_9));
  OAI21XL g96(.A0 (n_5), .A1 (x[2]), .B0 (n_6), .Y (sum[2]));
  NAND2BXL g97(.AN (n_5), .B (x[2]), .Y (n_7));
  NAND2XL g98(.A (x[2]), .B (n_5), .Y (n_6));
  AOI22XL g99(.A0 (n_3), .A1 (n_1), .B0 (y[1]), .B1 (x[1]), .Y (n_5));
  MXI2XL g100(.A (n_0), .B (n_3), .S0 (n_1), .Y (sum[1]));
  CLKINVX1 g101(.A (n_0), .Y (n_3));
  CLKXOR2X1 g102(.A (x[0]), .B (y[0]), .Y (sum[0]));
  CLKXOR2X1 g103(.A (x[1]), .B (y[1]), .Y (n_1));
  NAND2XL g104(.A (x[0]), .B (y[0]), .Y (n_0));
endmodule

module sixba_2(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_1, n_2, n_4, n_6, n_7, n_8, n_10;
  OAI21XL g114(.A0 (n_8), .A1 (y[5]), .B0 (n_10), .Y (sum[5]));
  NAND2XL g115(.A (y[5]), .B (n_8), .Y (n_10));
  OAI21XL g116(.A0 (n_6), .A1 (y[4]), .B0 (n_7), .Y (sum[4]));
  NAND2BXL g117(.AN (n_6), .B (y[4]), .Y (n_8));
  NAND2XL g118(.A (y[4]), .B (n_6), .Y (n_7));
  AOI22XL g119(.A0 (n_4), .A1 (n_2), .B0 (x[3]), .B1 (y[3]), .Y (n_6));
  MXI2XL g120(.A (n_1), .B (n_4), .S0 (n_2), .Y (sum[3]));
  CLKINVX1 g121(.A (n_1), .Y (n_4));
  CLKXOR2X1 g122(.A (y[2]), .B (x[2]), .Y (sum[2]));
  CLKXOR2X1 g123(.A (y[3]), .B (x[3]), .Y (n_2));
  NAND2XL g124(.A (y[2]), .B (x[2]), .Y (n_1));
endmodule

module sixba_3(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_0, n_2, n_3, n_4, n_5, n_7, n_8, n_10;
  wire n_11, n_13, n_14, n_15, n_17;
  OAI21XL g186(.A0 (n_15), .A1 (y[5]), .B0 (n_17), .Y (sum[5]));
  NAND2XL g187(.A (y[5]), .B (n_15), .Y (n_17));
  OAI21XL g188(.A0 (n_13), .A1 (y[4]), .B0 (n_14), .Y (sum[4]));
  NAND2BXL g189(.AN (n_13), .B (y[4]), .Y (n_15));
  NAND2XL g190(.A (y[4]), .B (n_13), .Y (n_14));
  AOI22XL g191(.A0 (n_11), .A1 (n_3), .B0 (x[3]), .B1 (y[3]), .Y
       (n_13));
  MXI2XL g192(.A (n_10), .B (n_11), .S0 (n_3), .Y (sum[3]));
  CLKINVX1 g193(.A (n_10), .Y (n_11));
  AOI22XL g194(.A0 (n_4), .A1 (n_8), .B0 (x[2]), .B1 (y[2]), .Y (n_10));
  MXI2XL g195(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[2]));
  CLKINVX1 g196(.A (n_7), .Y (n_8));
  AOI22XL g197(.A0 (n_2), .A1 (n_5), .B0 (x[1]), .B1 (y[1]), .Y (n_7));
  MXI2XL g198(.A (n_0), .B (n_5), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g199(.A (n_0), .Y (n_5));
  CLKXOR2X1 g200(.A (y[2]), .B (x[2]), .Y (n_4));
  CLKXOR2X1 g201(.A (y[3]), .B (x[3]), .Y (n_3));
  CLKXOR2X1 g202(.A (y[0]), .B (x[0]), .Y (sum[0]));
  CLKXOR2X1 g203(.A (y[1]), .B (x[1]), .Y (n_2));
  NAND2XL g204(.A (y[0]), .B (x[0]), .Y (n_0));
endmodule

module vedic_4_x_4_1(a, b, c);
  input [3:0] a, b;
  output [7:0] c;
  wire [3:0] a, b;
  wire [7:0] c;
  wire [3:0] q0;
  wire [3:0] q1;
  wire [3:0] q2;
  wire [3:0] q3;
  wire [3:0] q4;
  wire [5:0] q5;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z11,
       UNCONNECTED_HIER_Z12, UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14;
  wire UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18;
  vedic_2_x_2_4 z1(.a (a[1:0]), .b (b[1:0]), .c ({q0[3:2], c[1:0]}));
  vedic_2_x_2_5 z2(.a (a[3:2]), .b (b[1:0]), .c (q1));
  vedic_2_x_2_6 z3(.a (a[1:0]), .b (b[3:2]), .c (q2));
  vedic_2_x_2_7 z4(.a (a[3:2]), .b (b[3:2]), .c (q3));
  fourba_1 z5(.x (q1), .y ({UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9,
       q0[3:2]}), .sum (q4));
  sixba_2 z6(.x ({UNCONNECTED_HIER_Z14, UNCONNECTED_HIER_Z13, q2[3:2],
       UNCONNECTED_HIER_Z12, UNCONNECTED_HIER_Z11}), .y ({q3,
       UNCONNECTED_HIER_Z16, UNCONNECTED_HIER_Z15}), .sum ({q5[5:2],
       UNCONNECTED2, UNCONNECTED1}));
  sixba_3 z7(.x ({UNCONNECTED_HIER_Z18, UNCONNECTED_HIER_Z17, q4}), .y
       ({q5[5:2], q2[1:0]}), .sum (c[7:2]));
endmodule

module ha_16(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_17(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_8(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_16 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_17 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_18(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_19(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_9(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_18 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_19 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_20(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_21(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_10(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_20 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_21 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_22(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_23(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_11(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_22 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_23 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module fourba_2(x, y, sum);
  input [3:0] x, y;
  output [3:0] sum;
  wire [3:0] x, y;
  wire [3:0] sum;
  wire n_0, n_1, n_3, n_5, n_6, n_7, n_9;
  OAI21XL g94(.A0 (n_7), .A1 (x[3]), .B0 (n_9), .Y (sum[3]));
  NAND2XL g95(.A (x[3]), .B (n_7), .Y (n_9));
  OAI21XL g96(.A0 (n_5), .A1 (x[2]), .B0 (n_6), .Y (sum[2]));
  NAND2BXL g97(.AN (n_5), .B (x[2]), .Y (n_7));
  NAND2XL g98(.A (x[2]), .B (n_5), .Y (n_6));
  AOI22XL g99(.A0 (n_3), .A1 (n_1), .B0 (y[1]), .B1 (x[1]), .Y (n_5));
  MXI2XL g100(.A (n_0), .B (n_3), .S0 (n_1), .Y (sum[1]));
  CLKINVX1 g101(.A (n_0), .Y (n_3));
  CLKXOR2X1 g102(.A (x[0]), .B (y[0]), .Y (sum[0]));
  CLKXOR2X1 g103(.A (x[1]), .B (y[1]), .Y (n_1));
  NAND2XL g104(.A (x[0]), .B (y[0]), .Y (n_0));
endmodule

module sixba_4(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_1, n_2, n_4, n_6, n_7, n_8, n_10;
  OAI21XL g114(.A0 (n_8), .A1 (y[5]), .B0 (n_10), .Y (sum[5]));
  NAND2XL g115(.A (y[5]), .B (n_8), .Y (n_10));
  OAI21XL g116(.A0 (n_6), .A1 (y[4]), .B0 (n_7), .Y (sum[4]));
  NAND2BXL g117(.AN (n_6), .B (y[4]), .Y (n_8));
  NAND2XL g118(.A (y[4]), .B (n_6), .Y (n_7));
  AOI22XL g119(.A0 (n_4), .A1 (n_2), .B0 (x[3]), .B1 (y[3]), .Y (n_6));
  MXI2XL g120(.A (n_1), .B (n_4), .S0 (n_2), .Y (sum[3]));
  CLKINVX1 g121(.A (n_1), .Y (n_4));
  CLKXOR2X1 g122(.A (y[2]), .B (x[2]), .Y (sum[2]));
  CLKXOR2X1 g123(.A (y[3]), .B (x[3]), .Y (n_2));
  NAND2XL g124(.A (y[2]), .B (x[2]), .Y (n_1));
endmodule

module sixba_5(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_0, n_2, n_3, n_4, n_5, n_7, n_8, n_10;
  wire n_11, n_13, n_14, n_15, n_17;
  OAI21XL g186(.A0 (n_15), .A1 (y[5]), .B0 (n_17), .Y (sum[5]));
  NAND2XL g187(.A (y[5]), .B (n_15), .Y (n_17));
  OAI21XL g188(.A0 (n_13), .A1 (y[4]), .B0 (n_14), .Y (sum[4]));
  NAND2BXL g189(.AN (n_13), .B (y[4]), .Y (n_15));
  NAND2XL g190(.A (y[4]), .B (n_13), .Y (n_14));
  AOI22XL g191(.A0 (n_11), .A1 (n_3), .B0 (x[3]), .B1 (y[3]), .Y
       (n_13));
  MXI2XL g192(.A (n_10), .B (n_11), .S0 (n_3), .Y (sum[3]));
  CLKINVX1 g193(.A (n_10), .Y (n_11));
  AOI22XL g194(.A0 (n_4), .A1 (n_8), .B0 (x[2]), .B1 (y[2]), .Y (n_10));
  MXI2XL g195(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[2]));
  CLKINVX1 g196(.A (n_7), .Y (n_8));
  AOI22XL g197(.A0 (n_2), .A1 (n_5), .B0 (x[1]), .B1 (y[1]), .Y (n_7));
  MXI2XL g198(.A (n_0), .B (n_5), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g199(.A (n_0), .Y (n_5));
  CLKXOR2X1 g200(.A (y[2]), .B (x[2]), .Y (n_4));
  CLKXOR2X1 g201(.A (y[3]), .B (x[3]), .Y (n_3));
  CLKXOR2X1 g202(.A (y[0]), .B (x[0]), .Y (sum[0]));
  CLKXOR2X1 g203(.A (y[1]), .B (x[1]), .Y (n_2));
  NAND2XL g204(.A (y[0]), .B (x[0]), .Y (n_0));
endmodule

module vedic_4_x_4_2(a, b, c);
  input [3:0] a, b;
  output [7:0] c;
  wire [3:0] a, b;
  wire [7:0] c;
  wire [3:0] q0;
  wire [3:0] q1;
  wire [3:0] q2;
  wire [3:0] q3;
  wire [3:0] q4;
  wire [5:0] q5;
  wire UNCONNECTED3, UNCONNECTED4, UNCONNECTED_HIER_Z19,
       UNCONNECTED_HIER_Z20, UNCONNECTED_HIER_Z21,
       UNCONNECTED_HIER_Z22, UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z24;
  wire UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z28;
  vedic_2_x_2_8 z1(.a (a[1:0]), .b (b[1:0]), .c ({q0[3:2], c[1:0]}));
  vedic_2_x_2_9 z2(.a (a[3:2]), .b (b[1:0]), .c (q1));
  vedic_2_x_2_10 z3(.a (a[1:0]), .b (b[3:2]), .c (q2));
  vedic_2_x_2_11 z4(.a (a[3:2]), .b (b[3:2]), .c (q3));
  fourba_2 z5(.x (q1), .y ({UNCONNECTED_HIER_Z20, UNCONNECTED_HIER_Z19,
       q0[3:2]}), .sum (q4));
  sixba_4 z6(.x ({UNCONNECTED_HIER_Z24, UNCONNECTED_HIER_Z23, q2[3:2],
       UNCONNECTED_HIER_Z22, UNCONNECTED_HIER_Z21}), .y ({q3,
       UNCONNECTED_HIER_Z26, UNCONNECTED_HIER_Z25}), .sum ({q5[5:2],
       UNCONNECTED4, UNCONNECTED3}));
  sixba_5 z7(.x ({UNCONNECTED_HIER_Z28, UNCONNECTED_HIER_Z27, q4}), .y
       ({q5[5:2], q2[1:0]}), .sum (c[7:2]));
endmodule

module ha_24(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_25(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_12(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_24 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_25 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_26(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_27(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_13(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_26 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_27 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_28(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_29(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_14(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_28 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_29 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module ha_30(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (x), .B (y), .CO (carry), .S (sum));
endmodule

module ha_31(x, y, sum, carry);
  input x, y;
  output sum, carry;
  wire x, y;
  wire sum, carry;
  ADDHXL g17(.A (y), .B (x), .CO (carry), .S (sum));
endmodule

module vedic_2_x_2_15(a, b, c);
  input [1:0] a, b;
  output [3:0] c;
  wire [1:0] a, b;
  wire [3:0] c;
  wire n_8, n_9, n_10, temp;
  ha_30 z1(.x (n_10), .y (n_9), .sum (c[1]), .carry (temp));
  ha_31 z2(.x (temp), .y (n_8), .sum (c[2]), .carry (c[3]));
  AND2X1 g29(.A (b[0]), .B (a[0]), .Y (c[0]));
  AND2X1 g30(.A (b[0]), .B (a[1]), .Y (n_10));
  AND2X1 g31(.A (b[1]), .B (a[1]), .Y (n_8));
  AND2X1 g32(.A (b[1]), .B (a[0]), .Y (n_9));
endmodule

module fourba_3(x, y, sum);
  input [3:0] x, y;
  output [3:0] sum;
  wire [3:0] x, y;
  wire [3:0] sum;
  wire n_0, n_1, n_3, n_5, n_6, n_7, n_9;
  OAI21XL g94(.A0 (n_7), .A1 (x[3]), .B0 (n_9), .Y (sum[3]));
  NAND2XL g95(.A (x[3]), .B (n_7), .Y (n_9));
  OAI21XL g96(.A0 (n_5), .A1 (x[2]), .B0 (n_6), .Y (sum[2]));
  NAND2BXL g97(.AN (n_5), .B (x[2]), .Y (n_7));
  NAND2XL g98(.A (x[2]), .B (n_5), .Y (n_6));
  AOI22XL g99(.A0 (n_3), .A1 (n_1), .B0 (y[1]), .B1 (x[1]), .Y (n_5));
  MXI2XL g100(.A (n_0), .B (n_3), .S0 (n_1), .Y (sum[1]));
  CLKINVX1 g101(.A (n_0), .Y (n_3));
  CLKXOR2X1 g102(.A (x[0]), .B (y[0]), .Y (sum[0]));
  CLKXOR2X1 g103(.A (x[1]), .B (y[1]), .Y (n_1));
  NAND2XL g104(.A (x[0]), .B (y[0]), .Y (n_0));
endmodule

module sixba_6(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_1, n_2, n_4, n_6, n_7, n_8, n_10;
  OAI21XL g114(.A0 (n_8), .A1 (y[5]), .B0 (n_10), .Y (sum[5]));
  NAND2XL g115(.A (y[5]), .B (n_8), .Y (n_10));
  OAI21XL g116(.A0 (n_6), .A1 (y[4]), .B0 (n_7), .Y (sum[4]));
  NAND2BXL g117(.AN (n_6), .B (y[4]), .Y (n_8));
  NAND2XL g118(.A (y[4]), .B (n_6), .Y (n_7));
  AOI22XL g119(.A0 (n_4), .A1 (n_2), .B0 (x[3]), .B1 (y[3]), .Y (n_6));
  MXI2XL g120(.A (n_1), .B (n_4), .S0 (n_2), .Y (sum[3]));
  CLKINVX1 g121(.A (n_1), .Y (n_4));
  CLKXOR2X1 g122(.A (y[2]), .B (x[2]), .Y (sum[2]));
  CLKXOR2X1 g123(.A (y[3]), .B (x[3]), .Y (n_2));
  NAND2XL g124(.A (y[2]), .B (x[2]), .Y (n_1));
endmodule

module sixba_7(x, y, sum);
  input [5:0] x, y;
  output [5:0] sum;
  wire [5:0] x, y;
  wire [5:0] sum;
  wire n_0, n_2, n_3, n_4, n_5, n_7, n_8, n_10;
  wire n_11, n_13, n_14, n_15, n_17;
  OAI21XL g186(.A0 (n_15), .A1 (y[5]), .B0 (n_17), .Y (sum[5]));
  NAND2XL g187(.A (y[5]), .B (n_15), .Y (n_17));
  OAI21XL g188(.A0 (n_13), .A1 (y[4]), .B0 (n_14), .Y (sum[4]));
  NAND2BXL g189(.AN (n_13), .B (y[4]), .Y (n_15));
  NAND2XL g190(.A (y[4]), .B (n_13), .Y (n_14));
  AOI22XL g191(.A0 (n_11), .A1 (n_3), .B0 (x[3]), .B1 (y[3]), .Y
       (n_13));
  MXI2XL g192(.A (n_10), .B (n_11), .S0 (n_3), .Y (sum[3]));
  CLKINVX1 g193(.A (n_10), .Y (n_11));
  AOI22XL g194(.A0 (n_4), .A1 (n_8), .B0 (x[2]), .B1 (y[2]), .Y (n_10));
  MXI2XL g195(.A (n_7), .B (n_8), .S0 (n_4), .Y (sum[2]));
  CLKINVX1 g196(.A (n_7), .Y (n_8));
  AOI22XL g197(.A0 (n_2), .A1 (n_5), .B0 (x[1]), .B1 (y[1]), .Y (n_7));
  MXI2XL g198(.A (n_0), .B (n_5), .S0 (n_2), .Y (sum[1]));
  CLKINVX1 g199(.A (n_0), .Y (n_5));
  CLKXOR2X1 g200(.A (y[2]), .B (x[2]), .Y (n_4));
  CLKXOR2X1 g201(.A (y[3]), .B (x[3]), .Y (n_3));
  CLKXOR2X1 g202(.A (y[0]), .B (x[0]), .Y (sum[0]));
  CLKXOR2X1 g203(.A (y[1]), .B (x[1]), .Y (n_2));
  NAND2XL g204(.A (y[0]), .B (x[0]), .Y (n_0));
endmodule

module vedic_4_x_4_3(a, b, c);
  input [3:0] a, b;
  output [7:0] c;
  wire [3:0] a, b;
  wire [7:0] c;
  wire [3:0] q0;
  wire [3:0] q1;
  wire [3:0] q2;
  wire [3:0] q3;
  wire [3:0] q4;
  wire [5:0] q5;
  wire UNCONNECTED5, UNCONNECTED6, UNCONNECTED_HIER_Z29,
       UNCONNECTED_HIER_Z30, UNCONNECTED_HIER_Z31,
       UNCONNECTED_HIER_Z32, UNCONNECTED_HIER_Z33, UNCONNECTED_HIER_Z34;
  wire UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z36,
       UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z38;
  vedic_2_x_2_12 z1(.a (a[1:0]), .b (b[1:0]), .c ({q0[3:2], c[1:0]}));
  vedic_2_x_2_13 z2(.a (a[3:2]), .b (b[1:0]), .c (q1));
  vedic_2_x_2_14 z3(.a (a[1:0]), .b (b[3:2]), .c (q2));
  vedic_2_x_2_15 z4(.a (a[3:2]), .b (b[3:2]), .c (q3));
  fourba_3 z5(.x (q1), .y ({UNCONNECTED_HIER_Z30, UNCONNECTED_HIER_Z29,
       q0[3:2]}), .sum (q4));
  sixba_6 z6(.x ({UNCONNECTED_HIER_Z34, UNCONNECTED_HIER_Z33, q2[3:2],
       UNCONNECTED_HIER_Z32, UNCONNECTED_HIER_Z31}), .y ({q3,
       UNCONNECTED_HIER_Z36, UNCONNECTED_HIER_Z35}), .sum ({q5[5:2],
       UNCONNECTED6, UNCONNECTED5}));
  sixba_7 z7(.x ({UNCONNECTED_HIER_Z38, UNCONNECTED_HIER_Z37, q4}), .y
       ({q5[5:2], q2[1:0]}), .sum (c[7:2]));
endmodule

module eightba(x, y, sum);
  input [7:0] x, y;
  output [7:0] sum;
  wire [7:0] x, y;
  wire [7:0] sum;
  wire n_0, n_2, n_3, n_4, n_5, n_7, n_8, n_10;
  wire n_11, n_13, n_14, n_15, n_17, n_18, n_20, n_21;
  wire n_23;
  OAI21XL g234(.A0 (n_21), .A1 (x[7]), .B0 (n_23), .Y (sum[7]));
  NAND2XL g235(.A (x[7]), .B (n_21), .Y (n_23));
  OAI21XL g236(.A0 (n_17), .A1 (x[6]), .B0 (n_20), .Y (sum[6]));
  NAND2BXL g237(.AN (n_17), .B (x[6]), .Y (n_21));
  NAND2XL g238(.A (x[6]), .B (n_17), .Y (n_20));
  OAI21XL g239(.A0 (n_15), .A1 (x[5]), .B0 (n_18), .Y (sum[5]));
  NAND2XL g240(.A (x[5]), .B (n_15), .Y (n_18));
  NAND2BXL g241(.AN (n_15), .B (x[5]), .Y (n_17));
  OAI21XL g242(.A0 (n_13), .A1 (x[4]), .B0 (n_14), .Y (sum[4]));
  NAND2BXL g243(.AN (n_13), .B (x[4]), .Y (n_15));
  NAND2XL g244(.A (x[4]), .B (n_13), .Y (n_14));
  AOI22XL g245(.A0 (n_11), .A1 (n_2), .B0 (y[3]), .B1 (x[3]), .Y
       (n_13));
  MXI2XL g246(.A (n_10), .B (n_11), .S0 (n_2), .Y (sum[3]));
  CLKINVX1 g247(.A (n_10), .Y (n_11));
  AOI22XL g248(.A0 (n_3), .A1 (n_8), .B0 (y[2]), .B1 (x[2]), .Y (n_10));
  MXI2XL g249(.A (n_7), .B (n_8), .S0 (n_3), .Y (sum[2]));
  CLKINVX1 g250(.A (n_7), .Y (n_8));
  AOI22XL g251(.A0 (n_4), .A1 (n_5), .B0 (y[1]), .B1 (x[1]), .Y (n_7));
  MXI2XL g252(.A (n_0), .B (n_5), .S0 (n_4), .Y (sum[1]));
  CLKINVX1 g253(.A (n_0), .Y (n_5));
  CLKXOR2X1 g254(.A (x[1]), .B (y[1]), .Y (n_4));
  CLKXOR2X1 g255(.A (x[2]), .B (y[2]), .Y (n_3));
  CLKXOR2X1 g256(.A (x[0]), .B (y[0]), .Y (sum[0]));
  CLKXOR2X1 g257(.A (x[3]), .B (y[3]), .Y (n_2));
  NAND2XL g258(.A (x[0]), .B (y[0]), .Y (n_0));
endmodule

module twelveba(x, y, sum);
  input [11:0] x, y;
  output [11:0] sum;
  wire [11:0] x, y;
  wire [11:0] sum;
  wire n_1, n_3, n_4, n_5, n_6, n_8, n_9, n_11;
  wire n_12, n_14, n_15, n_16, n_18, n_19, n_21, n_22;
  wire n_24;
  OAI21XL g314(.A0 (n_22), .A1 (y[11]), .B0 (n_24), .Y (sum[11]));
  NAND2XL g315(.A (y[11]), .B (n_22), .Y (n_24));
  OAI21XL g316(.A0 (n_18), .A1 (y[10]), .B0 (n_21), .Y (sum[10]));
  NAND2BXL g317(.AN (n_18), .B (y[10]), .Y (n_22));
  NAND2XL g318(.A (y[10]), .B (n_18), .Y (n_21));
  OAI21XL g319(.A0 (n_16), .A1 (y[9]), .B0 (n_19), .Y (sum[9]));
  NAND2XL g320(.A (y[9]), .B (n_16), .Y (n_19));
  NAND2BXL g321(.AN (n_16), .B (y[9]), .Y (n_18));
  OAI21XL g322(.A0 (n_14), .A1 (y[8]), .B0 (n_15), .Y (sum[8]));
  NAND2BXL g323(.AN (n_14), .B (y[8]), .Y (n_16));
  NAND2XL g324(.A (y[8]), .B (n_14), .Y (n_15));
  AOI22XL g325(.A0 (n_12), .A1 (n_3), .B0 (x[7]), .B1 (y[7]), .Y
       (n_14));
  MXI2XL g326(.A (n_11), .B (n_12), .S0 (n_3), .Y (sum[7]));
  CLKINVX1 g327(.A (n_11), .Y (n_12));
  AOI22XL g328(.A0 (n_4), .A1 (n_9), .B0 (x[6]), .B1 (y[6]), .Y (n_11));
  MXI2XL g329(.A (n_8), .B (n_9), .S0 (n_4), .Y (sum[6]));
  CLKINVX1 g330(.A (n_8), .Y (n_9));
  AOI22XL g331(.A0 (n_5), .A1 (n_6), .B0 (x[5]), .B1 (y[5]), .Y (n_8));
  MXI2XL g332(.A (n_1), .B (n_6), .S0 (n_5), .Y (sum[5]));
  CLKINVX1 g333(.A (n_1), .Y (n_6));
  CLKXOR2X1 g334(.A (y[5]), .B (x[5]), .Y (n_5));
  CLKXOR2X1 g335(.A (y[6]), .B (x[6]), .Y (n_4));
  CLKXOR2X1 g336(.A (y[4]), .B (x[4]), .Y (sum[4]));
  CLKXOR2X1 g337(.A (y[7]), .B (x[7]), .Y (n_3));
  NAND2XL g338(.A (y[4]), .B (x[4]), .Y (n_1));
endmodule

module twelveba_1(x, y, sum);
  input [11:0] x, y;
  output [11:0] sum;
  wire [11:0] x, y;
  wire [11:0] sum;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_11, n_12, n_14, n_15, n_17, n_18, n_20;
  wire n_21, n_23, n_24, n_26, n_27, n_29, n_30, n_31;
  wire n_33, n_34, n_36, n_37, n_39;
  OAI21XL g457(.A0 (n_37), .A1 (y[11]), .B0 (n_39), .Y (sum[11]));
  NAND2XL g458(.A (y[11]), .B (n_37), .Y (n_39));
  OAI21XL g459(.A0 (n_33), .A1 (y[10]), .B0 (n_36), .Y (sum[10]));
  NAND2BXL g460(.AN (n_33), .B (y[10]), .Y (n_37));
  NAND2XL g461(.A (y[10]), .B (n_33), .Y (n_36));
  OAI21XL g462(.A0 (n_31), .A1 (y[9]), .B0 (n_34), .Y (sum[9]));
  NAND2XL g463(.A (y[9]), .B (n_31), .Y (n_34));
  NAND2BXL g464(.AN (n_31), .B (y[9]), .Y (n_33));
  OAI21XL g465(.A0 (n_29), .A1 (y[8]), .B0 (n_30), .Y (sum[8]));
  NAND2BXL g466(.AN (n_29), .B (y[8]), .Y (n_31));
  NAND2XL g467(.A (y[8]), .B (n_29), .Y (n_30));
  AOI22XL g468(.A0 (n_27), .A1 (n_3), .B0 (x[7]), .B1 (y[7]), .Y
       (n_29));
  MXI2XL g469(.A (n_26), .B (n_27), .S0 (n_3), .Y (sum[7]));
  CLKINVX1 g470(.A (n_26), .Y (n_27));
  AOI22XL g471(.A0 (n_24), .A1 (n_8), .B0 (x[6]), .B1 (y[6]), .Y
       (n_26));
  MXI2XL g472(.A (n_23), .B (n_24), .S0 (n_8), .Y (sum[6]));
  CLKINVX1 g473(.A (n_23), .Y (n_24));
  AOI22XL g474(.A0 (n_21), .A1 (n_6), .B0 (x[5]), .B1 (y[5]), .Y
       (n_23));
  MXI2XL g475(.A (n_20), .B (n_21), .S0 (n_6), .Y (sum[5]));
  CLKINVX1 g476(.A (n_20), .Y (n_21));
  AOI22XL g477(.A0 (n_5), .A1 (n_18), .B0 (x[4]), .B1 (y[4]), .Y
       (n_20));
  MXI2XL g478(.A (n_17), .B (n_18), .S0 (n_5), .Y (sum[4]));
  CLKINVX1 g479(.A (n_17), .Y (n_18));
  AOI22XL g480(.A0 (n_15), .A1 (n_2), .B0 (x[3]), .B1 (y[3]), .Y
       (n_17));
  MXI2XL g481(.A (n_14), .B (n_15), .S0 (n_2), .Y (sum[3]));
  CLKINVX1 g482(.A (n_14), .Y (n_15));
  AOI22XL g483(.A0 (n_4), .A1 (n_12), .B0 (x[2]), .B1 (y[2]), .Y
       (n_14));
  MXI2XL g484(.A (n_11), .B (n_12), .S0 (n_4), .Y (sum[2]));
  CLKINVX1 g485(.A (n_11), .Y (n_12));
  AOI22XL g486(.A0 (n_7), .A1 (n_9), .B0 (x[1]), .B1 (y[1]), .Y (n_11));
  MXI2XL g487(.A (n_0), .B (n_9), .S0 (n_7), .Y (sum[1]));
  CLKINVX1 g488(.A (n_0), .Y (n_9));
  XOR2X1 g489(.A (x[6]), .B (y[6]), .Y (n_8));
  CLKXOR2X1 g490(.A (y[1]), .B (x[1]), .Y (n_7));
  CLKXOR2X1 g491(.A (y[5]), .B (x[5]), .Y (n_6));
  CLKXOR2X1 g492(.A (y[4]), .B (x[4]), .Y (n_5));
  CLKXOR2X1 g493(.A (y[0]), .B (x[0]), .Y (sum[0]));
  CLKXOR2X1 g494(.A (y[2]), .B (x[2]), .Y (n_4));
  CLKXOR2X1 g495(.A (y[7]), .B (x[7]), .Y (n_3));
  CLKXOR2X1 g496(.A (y[3]), .B (x[3]), .Y (n_2));
  NAND2XL g497(.A (y[0]), .B (x[0]), .Y (n_0));
endmodule

module Vedic_8B(a, b, c);
  input [7:0] a, b;
  output [15:0] c;
  wire [7:0] a, b;
  wire [15:0] c;
  wire [7:0] q0;
  wire [7:0] q1;
  wire [7:0] q2;
  wire [7:0] q3;
  wire [7:0] q4;
  wire [11:0] q5;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z40,
       UNCONNECTED_HIER_Z41, UNCONNECTED_HIER_Z42;
  wire UNCONNECTED_HIER_Z43, UNCONNECTED_HIER_Z44,
       UNCONNECTED_HIER_Z45, UNCONNECTED_HIER_Z46,
       UNCONNECTED_HIER_Z47, UNCONNECTED_HIER_Z48,
       UNCONNECTED_HIER_Z49, UNCONNECTED_HIER_Z50;
  wire UNCONNECTED_HIER_Z51, UNCONNECTED_HIER_Z52,
       UNCONNECTED_HIER_Z53, UNCONNECTED_HIER_Z54,
       UNCONNECTED_HIER_Z55, UNCONNECTED_HIER_Z56,
       UNCONNECTED_HIER_Z57, UNCONNECTED_HIER_Z58;
  vedic_4_x_4 z1(a[3:0], b[3:0], {q0[7:4], c[3:0]});
  vedic_4_x_4_1 z2(a[7:4], b[3:0], q1);
  vedic_4_x_4_2 z3(a[3:0], b[7:4], q2);
  vedic_4_x_4_3 z4(a[7:4], b[7:4], q3);
  eightba z5(q1, {UNCONNECTED_HIER_Z42, UNCONNECTED_HIER_Z41,
       UNCONNECTED_HIER_Z40, UNCONNECTED_HIER_Z39, q0[7:4]}, q4);
  twelveba z6({UNCONNECTED_HIER_Z50, UNCONNECTED_HIER_Z49,
       UNCONNECTED_HIER_Z48, UNCONNECTED_HIER_Z47, q2[7:4],
       UNCONNECTED_HIER_Z46, UNCONNECTED_HIER_Z45,
       UNCONNECTED_HIER_Z44, UNCONNECTED_HIER_Z43}, {q3,
       UNCONNECTED_HIER_Z54, UNCONNECTED_HIER_Z53,
       UNCONNECTED_HIER_Z52, UNCONNECTED_HIER_Z51}, {q5[11:4],
       UNCONNECTED10, UNCONNECTED9, UNCONNECTED8, UNCONNECTED7});
  twelveba_1 z7({UNCONNECTED_HIER_Z58, UNCONNECTED_HIER_Z57,
       UNCONNECTED_HIER_Z56, UNCONNECTED_HIER_Z55, q4}, {q5[11:4],
       q2[3:0]}, c[15:4]);
endmodule

