
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 25 2019 15:25:39 IST (Nov 25 2019 09:55:39 UTC)

// Verification Directory fv/Vedic_8B_Rev 

module BVPPG_Rev(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_1(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_2(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire UNCONNECTED_HIER_Z3, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev lev11(a1, b1, UNCONNECTED_HIER_Z, b2, UNCONNECTED_HIER_Z0,
       g1, UNCONNECTED, y1, UNCONNECTED0, j1);
  PG_Rev lev12(a2, b1, UNCONNECTED_HIER_Z1, UNCONNECTED1, g2, j2);
  PG_Rev_1 lev13(a2, b2, UNCONNECTED_HIER_Z2, g3, g4, j3);
  PG_Rev_2 lev21(j1, j2, UNCONNECTED_HIER_Z3, g5, y2, y3);
  FG_Rev lev22(y3, j3, UNCONNECTED2, y4);
endmodule

module BVPPG_Rev_1(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_4(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_5(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_6(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_1(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_1(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6,
       UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z7;
  wire UNCONNECTED_HIER_Z8, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_1 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z4), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z5), .y1 (g1), .y2 (UNCONNECTED3),
       .y3 (y1), .y4 (UNCONNECTED4), .y5 (j1));
  PG_Rev_4 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z6), .y1
       (UNCONNECTED5), .y2 (g2), .y3 (j2));
  PG_Rev_5 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z7), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_6 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z8), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_1 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED6), .y2 (y4));
endmodule

module BVPPG_Rev_2(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_7(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_8(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_9(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_2(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_2(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z11,
       UNCONNECTED_HIER_Z12;
  wire UNCONNECTED_HIER_Z13, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_2 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z9), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z10), .y1 (g1), .y2 (UNCONNECTED7),
       .y3 (y1), .y4 (UNCONNECTED8), .y5 (j1));
  PG_Rev_7 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z11), .y1
       (UNCONNECTED9), .y2 (g2), .y3 (j2));
  PG_Rev_8 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z12), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_9 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z13), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_2 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED10), .y2 (y4));
endmodule

module BVPPG_Rev_3(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2XL g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_10(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_11(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_12(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_3(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  CLKXOR2X1 g10(.A (x2), .B (x1), .Y (y2));
endmodule

module Vedic_2B_Rev_3(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14,
       UNCONNECTED_HIER_Z14, UNCONNECTED_HIER_Z15,
       UNCONNECTED_HIER_Z16, UNCONNECTED_HIER_Z17;
  wire UNCONNECTED_HIER_Z18, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_3 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z14), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z15), .y1 (g1), .y2 (UNCONNECTED11),
       .y3 (y1), .y4 (UNCONNECTED12), .y5 (j1));
  PG_Rev_10 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z16), .y1
       (UNCONNECTED13), .y2 (g2), .y3 (j2));
  PG_Rev_11 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z17), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_12 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z18), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_3 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED14), .y2 (y4));
endmodule

module PG_Rev_3(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_1(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_2(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module FA_four_Rev(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z22, g1, g2, g3, g4;
  wire g5, g6, g7, j1, j2, j3;
  PG_Rev_3 level1(b1, a1, UNCONNECTED_HIER_Z19, g1, y1, j1);
  HNG_Rev level2(j1, b2, a2, UNCONNECTED_HIER_Z20, g2, g3, y2, j2);
  HNG_Rev_1 level3(j2, b3, a3, UNCONNECTED_HIER_Z21, g4, g5, y3, j3);
  HNG_Rev_2 level4(j3, b4, a4, UNCONNECTED_HIER_Z22, g6, g7, y4, c);
endmodule

module PG_Rev_13(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_3(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x1), .B (x2), .CI (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_4(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x1), .B (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_5(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  CLKXOR2X1 g16(.A (x1), .B (x3), .Y (y3));
endmodule

module FA_four_Rev_1(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z24,
       UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z28, g1, g2;
  wire g3, g4, g5, g6, g7, j1, j2, j3;
  wire n_1;
  PG_Rev_13 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z23), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_3 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z24), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_4 level3(.x1 (j2), .x2 (UNCONNECTED_HIER_Z25), .x3 (a3), .x4
       (UNCONNECTED_HIER_Z26), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_5 level4(.x1 (j3), .x2 (UNCONNECTED_HIER_Z27), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z28), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (n_1));
endmodule

module PG_Rev_14(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_6(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_7(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x2), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_8(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  wire n_1, n_2;
  OAI21XL g32(.A0 (n_1), .A1 (x3), .B0 (n_2), .Y (y3));
  NAND2XL g33(.A (x3), .B (n_1), .Y (n_2));
  XNOR2X1 g34(.A (x2), .B (x1), .Y (n_1));
endmodule

module FA_four_Rev_2(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z30,
       UNCONNECTED_HIER_Z31, UNCONNECTED_HIER_Z32,
       UNCONNECTED_HIER_Z33, g1, g2, g3;
  wire g4, g5, g6, g7, j1, j2, j3, n_1;
  PG_Rev_14 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z29), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_6 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z30), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_7 level3(.x1 (j2), .x2 (b3), .x3 (UNCONNECTED_HIER_Z31), .x4
       (UNCONNECTED_HIER_Z32), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_8 level4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z33), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (n_1));
endmodule

module Vedic_4B_Rev(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, y5,
     y6, y7, y8);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, y5, y6, y7, y8;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, y5, y6, y7, y8;
  wire UNCONNECTED_HIER_Z34, UNCONNECTED_HIER_Z35,
       UNCONNECTED_HIER_Z36, c1, c2, c3, l1, l2;
  wire l3, l4, m1, m2, m3, m4, n_13, n_14;
  wire n_15, n_16, o3, o4, p1, p2, p3, p4;
  wire q3, q4;
  Vedic_2B_Rev num1(a3, a4, b3, b4, l1, l2, l3, l4);
  Vedic_2B_Rev_1 num2(a1, a2, b3, b4, m1, m2, m3, m4);
  Vedic_2B_Rev_2 num3(a3, a4, b1, b2, n_16, n_15, n_14, n_13);
  Vedic_2B_Rev_3 num4(a1, a2, b1, b2, y1, y2, o3, o4);
  FA_four_Rev num5(m1, m2, m3, m4, n_16, n_15, n_14, n_13, p1, p2, p3,
       p4, c1);
  FA_four_Rev_1 num6(p1, p2, p3, p4, o3, o4, UNCONNECTED_HIER_Z34,
       UNCONNECTED_HIER_Z35, y3, y4, q3, q4, c2);
  FA_four_Rev_2 num7(q3, q4, UNCONNECTED_HIER_Z36, c1, l1, l2, l3, l4,
       y5, y6, y7, y8, c3);
endmodule

module BVPPG_Rev_4(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_16(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_17(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_18(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_4(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_4(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z38,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z40;
  wire UNCONNECTED_HIER_Z41, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_4 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z37), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z38), .y1 (g1), .y2 (UNCONNECTED15),
       .y3 (y1), .y4 (UNCONNECTED16), .y5 (j1));
  PG_Rev_16 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z39), .y1
       (UNCONNECTED17), .y2 (g2), .y3 (j2));
  PG_Rev_17 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z40), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_18 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z41), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_4 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED18), .y2 (y4));
endmodule

module BVPPG_Rev_5(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_19(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_20(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_21(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_5(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_5(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22,
       UNCONNECTED_HIER_Z42, UNCONNECTED_HIER_Z43,
       UNCONNECTED_HIER_Z44, UNCONNECTED_HIER_Z45;
  wire UNCONNECTED_HIER_Z46, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_5 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z42), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z43), .y1 (g1), .y2 (UNCONNECTED19),
       .y3 (y1), .y4 (UNCONNECTED20), .y5 (j1));
  PG_Rev_19 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z44), .y1
       (UNCONNECTED21), .y2 (g2), .y3 (j2));
  PG_Rev_20 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z45), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_21 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z46), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_5 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED22), .y2 (y4));
endmodule

module BVPPG_Rev_6(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_22(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_23(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_24(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_6(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_6(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED_HIER_Z47, UNCONNECTED_HIER_Z48,
       UNCONNECTED_HIER_Z49, UNCONNECTED_HIER_Z50;
  wire UNCONNECTED_HIER_Z51, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_6 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z47), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z48), .y1 (g1), .y2 (UNCONNECTED23),
       .y3 (y1), .y4 (UNCONNECTED24), .y5 (j1));
  PG_Rev_22 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z49), .y1
       (UNCONNECTED25), .y2 (g2), .y3 (j2));
  PG_Rev_23 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z50), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_24 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z51), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_6 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED26), .y2 (y4));
endmodule

module BVPPG_Rev_7(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_25(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_26(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_27(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_7(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  CLKXOR2X1 g10(.A (x2), .B (x1), .Y (y2));
endmodule

module Vedic_2B_Rev_7(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30,
       UNCONNECTED_HIER_Z52, UNCONNECTED_HIER_Z53,
       UNCONNECTED_HIER_Z54, UNCONNECTED_HIER_Z55;
  wire UNCONNECTED_HIER_Z56, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_7 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z52), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z53), .y1 (g1), .y2 (UNCONNECTED27),
       .y3 (y1), .y4 (UNCONNECTED28), .y5 (j1));
  PG_Rev_25 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z54), .y1
       (UNCONNECTED29), .y2 (g2), .y3 (j2));
  PG_Rev_26 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z55), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_27 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z56), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_7 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED30), .y2 (y4));
endmodule

module PG_Rev_28(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_16(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_17(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_18(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module FA_four_Rev_3(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z57, UNCONNECTED_HIER_Z58,
       UNCONNECTED_HIER_Z59, UNCONNECTED_HIER_Z60, g1, g2, g3, g4;
  wire g5, g6, g7, j1, j2, j3;
  PG_Rev_28 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z57), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_16 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z58), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_17 level3(.x1 (j2), .x2 (b3), .x3 (a3), .x4
       (UNCONNECTED_HIER_Z59), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_18 level4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z60), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (c));
endmodule

module PG_Rev_29(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_19(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x1), .B (x2), .CI (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_20(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x1), .B (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_21(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  CLKXOR2X1 g16(.A (x1), .B (x3), .Y (y3));
endmodule

module FA_four_Rev_4(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z61, UNCONNECTED_HIER_Z62,
       UNCONNECTED_HIER_Z63, UNCONNECTED_HIER_Z64,
       UNCONNECTED_HIER_Z65, UNCONNECTED_HIER_Z66, g1, g2;
  wire g3, g4, g5, g6, g7, j1, j2, j3;
  wire n_1;
  PG_Rev_29 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z61), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_19 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z62), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_20 level3(.x1 (j2), .x2 (UNCONNECTED_HIER_Z63), .x3 (a3), .x4
       (UNCONNECTED_HIER_Z64), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_21 level4(.x1 (j3), .x2 (UNCONNECTED_HIER_Z65), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z66), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (n_1));
endmodule

module PG_Rev_30(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_22(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_23(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x2), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_24(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  wire n_1, n_2;
  OAI21XL g32(.A0 (n_1), .A1 (x3), .B0 (n_2), .Y (y3));
  NAND2XL g33(.A (x3), .B (n_1), .Y (n_2));
  XNOR2X1 g34(.A (x2), .B (x1), .Y (n_1));
endmodule

module FA_four_Rev_5(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z67, UNCONNECTED_HIER_Z68,
       UNCONNECTED_HIER_Z69, UNCONNECTED_HIER_Z70,
       UNCONNECTED_HIER_Z71, g1, g2, g3;
  wire g4, g5, g6, g7, j1, j2, j3, n_1;
  PG_Rev_30 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z67), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_22 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z68), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_23 level3(.x1 (j2), .x2 (b3), .x3 (UNCONNECTED_HIER_Z69), .x4
       (UNCONNECTED_HIER_Z70), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_24 level4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z71), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (n_1));
endmodule

module Vedic_4B_Rev_1(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4,
     y5, y6, y7, y8);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, y5, y6, y7, y8;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, y5, y6, y7, y8;
  wire UNCONNECTED_HIER_Z72, UNCONNECTED_HIER_Z73,
       UNCONNECTED_HIER_Z74, c1, c2, c3, l1, l2;
  wire l3, l4, m1, m2, m3, m4, n_13, n_14;
  wire n_15, n_16, o3, o4, p1, p2, p3, p4;
  wire q3, q4;
  Vedic_2B_Rev_4 num1(.a1 (a3), .a2 (a4), .b1 (b3), .b2 (b4), .y1 (l1),
       .y2 (l2), .y3 (l3), .y4 (l4));
  Vedic_2B_Rev_5 num2(.a1 (a1), .a2 (a2), .b1 (b3), .b2 (b4), .y1 (m1),
       .y2 (m2), .y3 (m3), .y4 (m4));
  Vedic_2B_Rev_6 num3(.a1 (a3), .a2 (a4), .b1 (b1), .b2 (b2), .y1
       (n_16), .y2 (n_15), .y3 (n_14), .y4 (n_13));
  Vedic_2B_Rev_7 num4(.a1 (a1), .a2 (a2), .b1 (b1), .b2 (b2), .y1 (y1),
       .y2 (y2), .y3 (o3), .y4 (o4));
  FA_four_Rev_3 num5(.a1 (m1), .a2 (m2), .a3 (m3), .a4 (m4), .b1
       (n_16), .b2 (n_15), .b3 (n_14), .b4 (n_13), .y1 (p1), .y2 (p2),
       .y3 (p3), .y4 (p4), .c (c1));
  FA_four_Rev_4 num6(.a1 (p1), .a2 (p2), .a3 (p3), .a4 (p4), .b1 (o3),
       .b2 (o4), .b3 (UNCONNECTED_HIER_Z72), .b4
       (UNCONNECTED_HIER_Z73), .y1 (y3), .y2 (y4), .y3 (q3), .y4 (q4),
       .c (c2));
  FA_four_Rev_5 num7(.a1 (q3), .a2 (q4), .a3 (UNCONNECTED_HIER_Z74),
       .a4 (c1), .b1 (l1), .b2 (l2), .b3 (l3), .b4 (l4), .y1 (y5), .y2
       (y6), .y3 (y7), .y4 (y8), .c (c3));
endmodule

module BVPPG_Rev_8(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_31(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_32(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_33(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_8(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_8(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED_HIER_Z75, UNCONNECTED_HIER_Z76,
       UNCONNECTED_HIER_Z77, UNCONNECTED_HIER_Z78;
  wire UNCONNECTED_HIER_Z79, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_8 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z75), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z76), .y1 (g1), .y2 (UNCONNECTED31),
       .y3 (y1), .y4 (UNCONNECTED32), .y5 (j1));
  PG_Rev_31 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z77), .y1
       (UNCONNECTED33), .y2 (g2), .y3 (j2));
  PG_Rev_32 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z78), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_33 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z79), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_8 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED34), .y2 (y4));
endmodule

module BVPPG_Rev_9(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_34(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_35(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_36(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_9(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_9(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38,
       UNCONNECTED_HIER_Z80, UNCONNECTED_HIER_Z81,
       UNCONNECTED_HIER_Z82, UNCONNECTED_HIER_Z83;
  wire UNCONNECTED_HIER_Z84, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_9 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z80), .x4
       (b2), .x5 (UNCONNECTED_HIER_Z81), .y1 (g1), .y2 (UNCONNECTED35),
       .y3 (y1), .y4 (UNCONNECTED36), .y5 (j1));
  PG_Rev_34 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z82), .y1
       (UNCONNECTED37), .y2 (g2), .y3 (j2));
  PG_Rev_35 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z83), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_36 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z84), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_9 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED38), .y2 (y4));
endmodule

module BVPPG_Rev_10(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_37(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_38(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_39(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_10(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_10(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED_HIER_Z85, UNCONNECTED_HIER_Z86,
       UNCONNECTED_HIER_Z87, UNCONNECTED_HIER_Z88;
  wire UNCONNECTED_HIER_Z89, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_10 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z85),
       .x4 (b2), .x5 (UNCONNECTED_HIER_Z86), .y1 (g1), .y2
       (UNCONNECTED39), .y3 (y1), .y4 (UNCONNECTED40), .y5 (j1));
  PG_Rev_37 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z87), .y1
       (UNCONNECTED41), .y2 (g2), .y3 (j2));
  PG_Rev_38 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z88), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_39 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z89), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_10 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED42), .y2 (y4));
endmodule

module BVPPG_Rev_11(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_40(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_41(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_42(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_11(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  CLKXOR2X1 g10(.A (x2), .B (x1), .Y (y2));
endmodule

module Vedic_2B_Rev_11(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46,
       UNCONNECTED_HIER_Z90, UNCONNECTED_HIER_Z91,
       UNCONNECTED_HIER_Z92, UNCONNECTED_HIER_Z93;
  wire UNCONNECTED_HIER_Z94, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_11 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z90),
       .x4 (b2), .x5 (UNCONNECTED_HIER_Z91), .y1 (g1), .y2
       (UNCONNECTED43), .y3 (y1), .y4 (UNCONNECTED44), .y5 (j1));
  PG_Rev_40 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z92), .y1
       (UNCONNECTED45), .y2 (g2), .y3 (j2));
  PG_Rev_41 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z93), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_42 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z94), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_11 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED46), .y2 (y4));
endmodule

module PG_Rev_43(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_25(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_26(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_27(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module FA_four_Rev_6(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z95, UNCONNECTED_HIER_Z96,
       UNCONNECTED_HIER_Z97, UNCONNECTED_HIER_Z98, g1, g2, g3, g4;
  wire g5, g6, g7, j1, j2, j3;
  PG_Rev_43 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z95), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_25 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z96), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_26 level3(.x1 (j2), .x2 (b3), .x3 (a3), .x4
       (UNCONNECTED_HIER_Z97), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_27 level4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z98), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (c));
endmodule

module PG_Rev_44(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_28(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x1), .B (x2), .CI (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_29(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x1), .B (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_30(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  CLKXOR2X1 g16(.A (x1), .B (x3), .Y (y3));
endmodule

module FA_four_Rev_7(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z99, UNCONNECTED_HIER_Z100,
       UNCONNECTED_HIER_Z101, UNCONNECTED_HIER_Z102,
       UNCONNECTED_HIER_Z103, UNCONNECTED_HIER_Z104, g1, g2;
  wire g3, g4, g5, g6, g7, j1, j2, j3;
  wire n_1;
  PG_Rev_44 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z99), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_28 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z100), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_29 level3(.x1 (j2), .x2 (UNCONNECTED_HIER_Z101), .x3 (a3),
       .x4 (UNCONNECTED_HIER_Z102), .y1 (g4), .y2 (g5), .y3 (y3), .y4
       (j3));
  HNG_Rev_30 level4(.x1 (j3), .x2 (UNCONNECTED_HIER_Z103), .x3 (a4),
       .x4 (UNCONNECTED_HIER_Z104), .y1 (g6), .y2 (g7), .y3 (y4), .y4
       (n_1));
endmodule

module PG_Rev_45(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_31(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_32(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x2), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_33(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  wire n_1, n_2;
  OAI21XL g32(.A0 (n_1), .A1 (x3), .B0 (n_2), .Y (y3));
  NAND2XL g33(.A (x3), .B (n_1), .Y (n_2));
  XNOR2X1 g34(.A (x2), .B (x1), .Y (n_1));
endmodule

module FA_four_Rev_8(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z105, UNCONNECTED_HIER_Z106,
       UNCONNECTED_HIER_Z107, UNCONNECTED_HIER_Z108,
       UNCONNECTED_HIER_Z109, g1, g2, g3;
  wire g4, g5, g6, g7, j1, j2, j3, n_1;
  PG_Rev_45 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z105), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_31 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z106), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_32 level3(.x1 (j2), .x2 (b3), .x3 (UNCONNECTED_HIER_Z107),
       .x4 (UNCONNECTED_HIER_Z108), .y1 (g4), .y2 (g5), .y3 (y3), .y4
       (j3));
  HNG_Rev_33 level4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z109), .y1 (g6), .y2 (g7), .y3 (y4), .y4
       (n_1));
endmodule

module Vedic_4B_Rev_2(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4,
     y5, y6, y7, y8);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, y5, y6, y7, y8;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, y5, y6, y7, y8;
  wire UNCONNECTED_HIER_Z110, UNCONNECTED_HIER_Z111,
       UNCONNECTED_HIER_Z112, c1, c2, c3, l1, l2;
  wire l3, l4, m1, m2, m3, m4, n_13, n_14;
  wire n_15, n_16, o3, o4, p1, p2, p3, p4;
  wire q3, q4;
  Vedic_2B_Rev_8 num1(.a1 (a3), .a2 (a4), .b1 (b3), .b2 (b4), .y1 (l1),
       .y2 (l2), .y3 (l3), .y4 (l4));
  Vedic_2B_Rev_9 num2(.a1 (a1), .a2 (a2), .b1 (b3), .b2 (b4), .y1 (m1),
       .y2 (m2), .y3 (m3), .y4 (m4));
  Vedic_2B_Rev_10 num3(.a1 (a3), .a2 (a4), .b1 (b1), .b2 (b2), .y1
       (n_16), .y2 (n_15), .y3 (n_14), .y4 (n_13));
  Vedic_2B_Rev_11 num4(.a1 (a1), .a2 (a2), .b1 (b1), .b2 (b2), .y1
       (y1), .y2 (y2), .y3 (o3), .y4 (o4));
  FA_four_Rev_6 num5(.a1 (m1), .a2 (m2), .a3 (m3), .a4 (m4), .b1
       (n_16), .b2 (n_15), .b3 (n_14), .b4 (n_13), .y1 (p1), .y2 (p2),
       .y3 (p3), .y4 (p4), .c (c1));
  FA_four_Rev_7 num6(.a1 (p1), .a2 (p2), .a3 (p3), .a4 (p4), .b1 (o3),
       .b2 (o4), .b3 (UNCONNECTED_HIER_Z110), .b4
       (UNCONNECTED_HIER_Z111), .y1 (y3), .y2 (y4), .y3 (q3), .y4 (q4),
       .c (c2));
  FA_four_Rev_8 num7(.a1 (q3), .a2 (q4), .a3 (UNCONNECTED_HIER_Z112),
       .a4 (c1), .b1 (l1), .b2 (l2), .b3 (l3), .b4 (l4), .y1 (y5), .y2
       (y6), .y3 (y7), .y4 (y8), .c (c3));
endmodule

module BVPPG_Rev_12(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_46(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_47(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_48(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_12(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_12(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED_HIER_Z113, UNCONNECTED_HIER_Z114,
       UNCONNECTED_HIER_Z115, UNCONNECTED_HIER_Z116;
  wire UNCONNECTED_HIER_Z117, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_12 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z113),
       .x4 (b2), .x5 (UNCONNECTED_HIER_Z114), .y1 (g1), .y2
       (UNCONNECTED47), .y3 (y1), .y4 (UNCONNECTED48), .y5 (j1));
  PG_Rev_46 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z115), .y1
       (UNCONNECTED49), .y2 (g2), .y3 (j2));
  PG_Rev_47 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z116), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_48 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z117), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_12 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED50), .y2 (y4));
endmodule

module BVPPG_Rev_13(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_49(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_50(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_51(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_13(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_13(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54,
       UNCONNECTED_HIER_Z118, UNCONNECTED_HIER_Z119,
       UNCONNECTED_HIER_Z120, UNCONNECTED_HIER_Z121;
  wire UNCONNECTED_HIER_Z122, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_13 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z118),
       .x4 (b2), .x5 (UNCONNECTED_HIER_Z119), .y1 (g1), .y2
       (UNCONNECTED51), .y3 (y1), .y4 (UNCONNECTED52), .y5 (j1));
  PG_Rev_49 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z120), .y1
       (UNCONNECTED53), .y2 (g2), .y3 (j2));
  PG_Rev_50 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z121), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_51 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z122), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_13 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED54), .y2 (y4));
endmodule

module BVPPG_Rev_14(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_52(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_53(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_54(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_14(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  XOR2X1 g10(.A (x1), .B (x2), .Y (y2));
endmodule

module Vedic_2B_Rev_14(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED_HIER_Z123, UNCONNECTED_HIER_Z124,
       UNCONNECTED_HIER_Z125, UNCONNECTED_HIER_Z126;
  wire UNCONNECTED_HIER_Z127, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_14 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z123),
       .x4 (b2), .x5 (UNCONNECTED_HIER_Z124), .y1 (g1), .y2
       (UNCONNECTED55), .y3 (y1), .y4 (UNCONNECTED56), .y5 (j1));
  PG_Rev_52 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z125), .y1
       (UNCONNECTED57), .y2 (g2), .y3 (j2));
  PG_Rev_53 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z126), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_54 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z127), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_14 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED58), .y2 (y4));
endmodule

module BVPPG_Rev_15(x1, x2, x3, x4, x5, y1, y2, y3, y4, y5);
  input x1, x2, x3, x4, x5;
  output y1, y2, y3, y4, y5;
  wire x1, x2, x3, x4, x5;
  wire y1, y2, y3, y4, y5;
  AND2X1 g17(.A (x2), .B (x1), .Y (y3));
  AND2X1 g18(.A (x4), .B (x1), .Y (y5));
endmodule

module PG_Rev_55(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_56(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  AND2X1 g10(.A (x2), .B (x1), .Y (y3));
endmodule

module PG_Rev_57(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module FG_Rev_15(x1, x2, y1, y2);
  input x1, x2;
  output y1, y2;
  wire x1, x2;
  wire y1, y2;
  CLKXOR2X1 g10(.A (x2), .B (x1), .Y (y2));
endmodule

module Vedic_2B_Rev_15(a1, a2, b1, b2, y1, y2, y3, y4);
  input a1, a2, b1, b2;
  output y1, y2, y3, y4;
  wire a1, a2, b1, b2;
  wire y1, y2, y3, y4;
  wire UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62,
       UNCONNECTED_HIER_Z128, UNCONNECTED_HIER_Z129,
       UNCONNECTED_HIER_Z130, UNCONNECTED_HIER_Z131;
  wire UNCONNECTED_HIER_Z132, g1, g2, g3, g4, g5, j1, j2;
  wire j3;
  BVPPG_Rev_15 lev11(.x1 (a1), .x2 (b1), .x3 (UNCONNECTED_HIER_Z128),
       .x4 (b2), .x5 (UNCONNECTED_HIER_Z129), .y1 (g1), .y2
       (UNCONNECTED59), .y3 (y1), .y4 (UNCONNECTED60), .y5 (j1));
  PG_Rev_55 lev12(.x1 (a2), .x2 (b1), .x3 (UNCONNECTED_HIER_Z130), .y1
       (UNCONNECTED61), .y2 (g2), .y3 (j2));
  PG_Rev_56 lev13(.x1 (a2), .x2 (b2), .x3 (UNCONNECTED_HIER_Z131), .y1
       (g3), .y2 (g4), .y3 (j3));
  PG_Rev_57 lev21(.x1 (j1), .x2 (j2), .x3 (UNCONNECTED_HIER_Z132), .y1
       (g5), .y2 (y2), .y3 (y3));
  FG_Rev_15 lev22(.x1 (y3), .x2 (j3), .y1 (UNCONNECTED62), .y2 (y4));
endmodule

module PG_Rev_58(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_34(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_35(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_36(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module FA_four_Rev_9(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4, c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z133, UNCONNECTED_HIER_Z134,
       UNCONNECTED_HIER_Z135, UNCONNECTED_HIER_Z136, g1, g2, g3, g4;
  wire g5, g6, g7, j1, j2, j3;
  PG_Rev_58 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z133), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_34 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z134), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_35 level3(.x1 (j2), .x2 (b3), .x3 (a3), .x4
       (UNCONNECTED_HIER_Z135), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_36 level4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z136), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (c));
endmodule

module PG_Rev_59(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_37(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x1), .B (x2), .CI (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_38(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x1), .B (x3), .CO (y4), .S (y3));
endmodule

module HNG_Rev_39(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  CLKXOR2X1 g16(.A (x1), .B (x3), .Y (y3));
endmodule

module FA_four_Rev_10(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4,
     c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z137, UNCONNECTED_HIER_Z138,
       UNCONNECTED_HIER_Z139, UNCONNECTED_HIER_Z140,
       UNCONNECTED_HIER_Z141, UNCONNECTED_HIER_Z142, g1, g2;
  wire g3, g4, g5, g6, g7, j1, j2, j3;
  wire n_1;
  PG_Rev_59 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z137), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_37 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z138), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_38 level3(.x1 (j2), .x2 (UNCONNECTED_HIER_Z139), .x3 (a3),
       .x4 (UNCONNECTED_HIER_Z140), .y1 (g4), .y2 (g5), .y3 (y3), .y4
       (j3));
  HNG_Rev_39 level4(.x1 (j3), .x2 (UNCONNECTED_HIER_Z141), .x3 (a4),
       .x4 (UNCONNECTED_HIER_Z142), .y1 (g6), .y2 (g7), .y3 (y4), .y4
       (n_1));
endmodule

module PG_Rev_60(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_40(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_41(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x2), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_42(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  wire n_1, n_2;
  OAI21XL g32(.A0 (n_1), .A1 (x3), .B0 (n_2), .Y (y3));
  NAND2XL g33(.A (x3), .B (n_1), .Y (n_2));
  XNOR2X1 g34(.A (x2), .B (x1), .Y (n_1));
endmodule

module FA_four_Rev_11(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4,
     c);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, c;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, c;
  wire UNCONNECTED_HIER_Z143, UNCONNECTED_HIER_Z144,
       UNCONNECTED_HIER_Z145, UNCONNECTED_HIER_Z146,
       UNCONNECTED_HIER_Z147, g1, g2, g3;
  wire g4, g5, g6, g7, j1, j2, j3, n_1;
  PG_Rev_60 level1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z143), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_40 level2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z144), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_41 level3(.x1 (j2), .x2 (b3), .x3 (UNCONNECTED_HIER_Z145),
       .x4 (UNCONNECTED_HIER_Z146), .y1 (g4), .y2 (g5), .y3 (y3), .y4
       (j3));
  HNG_Rev_42 level4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z147), .y1 (g6), .y2 (g7), .y3 (y4), .y4
       (n_1));
endmodule

module Vedic_4B_Rev_3(a1, a2, a3, a4, b1, b2, b3, b4, y1, y2, y3, y4,
     y5, y6, y7, y8);
  input a1, a2, a3, a4, b1, b2, b3, b4;
  output y1, y2, y3, y4, y5, y6, y7, y8;
  wire a1, a2, a3, a4, b1, b2, b3, b4;
  wire y1, y2, y3, y4, y5, y6, y7, y8;
  wire UNCONNECTED_HIER_Z148, UNCONNECTED_HIER_Z149,
       UNCONNECTED_HIER_Z150, c1, c2, c3, l1, l2;
  wire l3, l4, m1, m2, m3, m4, n_13, n_14;
  wire n_15, n_16, o3, o4, p1, p2, p3, p4;
  wire q3, q4;
  Vedic_2B_Rev_12 num1(.a1 (a3), .a2 (a4), .b1 (b3), .b2 (b4), .y1
       (l1), .y2 (l2), .y3 (l3), .y4 (l4));
  Vedic_2B_Rev_13 num2(.a1 (a1), .a2 (a2), .b1 (b3), .b2 (b4), .y1
       (m1), .y2 (m2), .y3 (m3), .y4 (m4));
  Vedic_2B_Rev_14 num3(.a1 (a3), .a2 (a4), .b1 (b1), .b2 (b2), .y1
       (n_16), .y2 (n_15), .y3 (n_14), .y4 (n_13));
  Vedic_2B_Rev_15 num4(.a1 (a1), .a2 (a2), .b1 (b1), .b2 (b2), .y1
       (y1), .y2 (y2), .y3 (o3), .y4 (o4));
  FA_four_Rev_9 num5(.a1 (m1), .a2 (m2), .a3 (m3), .a4 (m4), .b1
       (n_16), .b2 (n_15), .b3 (n_14), .b4 (n_13), .y1 (p1), .y2 (p2),
       .y3 (p3), .y4 (p4), .c (c1));
  FA_four_Rev_10 num6(.a1 (p1), .a2 (p2), .a3 (p3), .a4 (p4), .b1 (o3),
       .b2 (o4), .b3 (UNCONNECTED_HIER_Z148), .b4
       (UNCONNECTED_HIER_Z149), .y1 (y3), .y2 (y4), .y3 (q3), .y4 (q4),
       .c (c2));
  FA_four_Rev_11 num7(.a1 (q3), .a2 (q4), .a3 (UNCONNECTED_HIER_Z150),
       .a4 (c1), .b1 (l1), .b2 (l2), .b3 (l3), .b4 (l4), .y1 (y5), .y2
       (y6), .y3 (y7), .y4 (y8), .c (c3));
endmodule

module PG_Rev_15(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x1), .B (x2), .CO (y3), .S (y2));
endmodule

module HNG_Rev_9(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_10(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_11(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_12(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x1), .CI (x2), .CO (y4), .S (y3));
endmodule

module HNG_Rev_13(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_14(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_15(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module FA_eight_Rev(a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5,
     b6, b7, b8, y1, y2, y3, y4, y5, y6, y7, y8, c);
  input a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8;
  output y1, y2, y3, y4, y5, y6, y7, y8, c;
  wire a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8;
  wire y1, y2, y3, y4, y5, y6, y7, y8, c;
  wire UNCONNECTED_HIER_Z151, UNCONNECTED_HIER_Z152,
       UNCONNECTED_HIER_Z153, UNCONNECTED_HIER_Z154,
       UNCONNECTED_HIER_Z155, UNCONNECTED_HIER_Z156,
       UNCONNECTED_HIER_Z157, UNCONNECTED_HIER_Z158;
  wire g1, g2, g3, g4, g5, g6, g7, g8;
  wire g9, g10, g11, g12, g13, g14, g15, j1;
  wire j2, j3, j4, j5, j6, j7;
  PG_Rev_15 leve1(b1, a1, UNCONNECTED_HIER_Z151, g1, y1, j1);
  HNG_Rev_9 leve2(j1, b2, a2, UNCONNECTED_HIER_Z152, g2, g3, y2, j2);
  HNG_Rev_10 leve3(j2, b3, a3, UNCONNECTED_HIER_Z153, g4, g5, y3, j3);
  HNG_Rev_11 leve4(j3, b4, a4, UNCONNECTED_HIER_Z154, g6, g7, y4, j4);
  HNG_Rev_12 leve5(j4, b5, a5, UNCONNECTED_HIER_Z155, g8, g9, y5, j5);
  HNG_Rev_13 leve6(j5, b6, a6, UNCONNECTED_HIER_Z156, g10, g11, y6, j6);
  HNG_Rev_14 leve7(j6, b7, a7, UNCONNECTED_HIER_Z157, g12, g13, y7, j7);
  HNG_Rev_15 leve8(j7, b8, a8, UNCONNECTED_HIER_Z158, g14, g15, y8, c);
endmodule

module PG_Rev_61(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x2), .B (x1), .CO (y3), .S (y2));
endmodule

module HNG_Rev_43(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x1), .CI (x2), .CO (y4), .S (y3));
endmodule

module HNG_Rev_44(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_45(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_46(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x3), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_47(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x3), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_48(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x3), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_49(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  CLKXOR2X1 g16(.A (x3), .B (x1), .Y (y3));
endmodule

module FA_eight_Rev_1(a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4,
     b5, b6, b7, b8, y1, y2, y3, y4, y5, y6, y7, y8, c);
  input a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8;
  output y1, y2, y3, y4, y5, y6, y7, y8, c;
  wire a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8;
  wire y1, y2, y3, y4, y5, y6, y7, y8, c;
  wire UNCONNECTED_HIER_Z159, UNCONNECTED_HIER_Z160,
       UNCONNECTED_HIER_Z161, UNCONNECTED_HIER_Z162,
       UNCONNECTED_HIER_Z163, UNCONNECTED_HIER_Z164,
       UNCONNECTED_HIER_Z165, UNCONNECTED_HIER_Z166;
  wire UNCONNECTED_HIER_Z167, UNCONNECTED_HIER_Z168,
       UNCONNECTED_HIER_Z169, UNCONNECTED_HIER_Z170, g1, g2, g3, g4;
  wire g5, g6, g7, g8, g9, g10, g11, g12;
  wire g13, g14, g15, j1, j2, j3, j4, j5;
  wire j6, j7, n_1;
  PG_Rev_61 leve1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z159), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_43 leve2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z160), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_44 leve3(.x1 (j2), .x2 (b3), .x3 (a3), .x4
       (UNCONNECTED_HIER_Z161), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_45 leve4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z162), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (j4));
  HNG_Rev_46 leve5(.x1 (j4), .x2 (UNCONNECTED_HIER_Z163), .x3 (a5), .x4
       (UNCONNECTED_HIER_Z164), .y1 (g8), .y2 (g9), .y3 (y5), .y4 (j5));
  HNG_Rev_47 leve6(.x1 (j5), .x2 (UNCONNECTED_HIER_Z165), .x3 (a6), .x4
       (UNCONNECTED_HIER_Z166), .y1 (g10), .y2 (g11), .y3 (y6), .y4
       (j6));
  HNG_Rev_48 leve7(.x1 (j6), .x2 (UNCONNECTED_HIER_Z167), .x3 (a7), .x4
       (UNCONNECTED_HIER_Z168), .y1 (g12), .y2 (g13), .y3 (y7), .y4
       (j7));
  HNG_Rev_49 leve8(.x1 (j7), .x2 (UNCONNECTED_HIER_Z169), .x3 (a8), .x4
       (UNCONNECTED_HIER_Z170), .y1 (g14), .y2 (g15), .y3 (y8), .y4
       (n_1));
endmodule

module PG_Rev_62(x1, x2, x3, y1, y2, y3);
  input x1, x2, x3;
  output y1, y2, y3;
  wire x1, x2, x3;
  wire y1, y2, y3;
  ADDHXL g18(.A (x2), .B (x1), .CO (y3), .S (y2));
endmodule

module HNG_Rev_50(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_51(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_52(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDFX1 g2(.A (x3), .B (x2), .CI (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_53(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x3), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_54(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x3), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_55(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  ADDHXL g22(.A (x3), .B (x1), .CO (y4), .S (y3));
endmodule

module HNG_Rev_56(x1, x2, x3, x4, y1, y2, y3, y4);
  input x1, x2, x3, x4;
  output y1, y2, y3, y4;
  wire x1, x2, x3, x4;
  wire y1, y2, y3, y4;
  wire n_1, n_2;
  OAI21XL g32(.A0 (n_1), .A1 (x3), .B0 (n_2), .Y (y3));
  NAND2XL g33(.A (x3), .B (n_1), .Y (n_2));
  XNOR2X1 g34(.A (x2), .B (x1), .Y (n_1));
endmodule

module FA_eight_Rev_2(a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4,
     b5, b6, b7, b8, y1, y2, y3, y4, y5, y6, y7, y8, c);
  input a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8;
  output y1, y2, y3, y4, y5, y6, y7, y8, c;
  wire a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8;
  wire y1, y2, y3, y4, y5, y6, y7, y8, c;
  wire UNCONNECTED_HIER_Z171, UNCONNECTED_HIER_Z172,
       UNCONNECTED_HIER_Z173, UNCONNECTED_HIER_Z174,
       UNCONNECTED_HIER_Z175, UNCONNECTED_HIER_Z176,
       UNCONNECTED_HIER_Z177, UNCONNECTED_HIER_Z178;
  wire UNCONNECTED_HIER_Z179, UNCONNECTED_HIER_Z180,
       UNCONNECTED_HIER_Z181, g1, g2, g3, g4, g5;
  wire g6, g7, g8, g9, g10, g11, g12, g13;
  wire g14, g15, j1, j2, j3, j4, j5, j6;
  wire j7, n_1;
  PG_Rev_62 leve1(.x1 (b1), .x2 (a1), .x3 (UNCONNECTED_HIER_Z171), .y1
       (g1), .y2 (y1), .y3 (j1));
  HNG_Rev_50 leve2(.x1 (j1), .x2 (b2), .x3 (a2), .x4
       (UNCONNECTED_HIER_Z172), .y1 (g2), .y2 (g3), .y3 (y2), .y4 (j2));
  HNG_Rev_51 leve3(.x1 (j2), .x2 (b3), .x3 (a3), .x4
       (UNCONNECTED_HIER_Z173), .y1 (g4), .y2 (g5), .y3 (y3), .y4 (j3));
  HNG_Rev_52 leve4(.x1 (j3), .x2 (b4), .x3 (a4), .x4
       (UNCONNECTED_HIER_Z174), .y1 (g6), .y2 (g7), .y3 (y4), .y4 (j4));
  HNG_Rev_53 leve5(.x1 (j4), .x2 (UNCONNECTED_HIER_Z175), .x3 (a5), .x4
       (UNCONNECTED_HIER_Z176), .y1 (g8), .y2 (g9), .y3 (y5), .y4 (j5));
  HNG_Rev_54 leve6(.x1 (j5), .x2 (UNCONNECTED_HIER_Z177), .x3 (a6), .x4
       (UNCONNECTED_HIER_Z178), .y1 (g10), .y2 (g11), .y3 (y6), .y4
       (j6));
  HNG_Rev_55 leve7(.x1 (j6), .x2 (UNCONNECTED_HIER_Z179), .x3 (a7), .x4
       (UNCONNECTED_HIER_Z180), .y1 (g12), .y2 (g13), .y3 (y7), .y4
       (j7));
  HNG_Rev_56 leve8(.x1 (j7), .x2 (b8), .x3 (a8), .x4
       (UNCONNECTED_HIER_Z181), .y1 (g14), .y2 (g15), .y3 (y8), .y4
       (n_1));
endmodule

module Vedic_8B_Rev(a, b, y);
  input [7:0] a, b;
  output [15:0] y;
  wire [7:0] a, b;
  wire [15:0] y;
  wire UNCONNECTED_HIER_Z182, UNCONNECTED_HIER_Z183,
       UNCONNECTED_HIER_Z184, UNCONNECTED_HIER_Z185,
       UNCONNECTED_HIER_Z186, UNCONNECTED_HIER_Z187,
       UNCONNECTED_HIER_Z188, c1;
  wire c2, c3, q4, q5, q6, q7, r0, r1;
  wire r2, r3, r4, r5, r6, r7, s0, s1;
  wire s2, s3, s4, s5, s6, s7, t0, t1;
  wire t2, t3, t4, t5, t6, t7, u0, u1;
  wire u2, u3, u4, u5, u6, u7, v4, v5;
  wire v6, v7;
  Vedic_4B_Rev index1(a[0], a[1], a[2], a[3], b[0], b[1], b[2], b[3],
       y[0], y[1], y[2], y[3], q4, q5, q6, q7);
  Vedic_4B_Rev_1 index2(a[0], a[1], a[2], a[3], b[4], b[5], b[6], b[7],
       r0, r1, r2, r3, r4, r5, r6, r7);
  Vedic_4B_Rev_2 index3(a[4], a[5], a[6], a[7], b[0], b[1], b[2], b[3],
       s0, s1, s2, s3, s4, s5, s6, s7);
  Vedic_4B_Rev_3 index4(a[4], a[5], a[6], a[7], b[4], b[5], b[6], b[7],
       t0, t1, t2, t3, t4, t5, t6, t7);
  FA_eight_Rev index5(r0, r1, r2, r3, r4, r5, r6, r7, s0, s1, s2, s3,
       s4, s5, s6, s7, u0, u1, u2, u3, u4, u5, u6, u7, c1);
  FA_eight_Rev_1 index6(u0, u1, u2, u3, u4, u5, u6, u7, q4, q5, q6, q7,
       UNCONNECTED_HIER_Z182, UNCONNECTED_HIER_Z183,
       UNCONNECTED_HIER_Z184, UNCONNECTED_HIER_Z185, y[4], y[5], y[6],
       y[7], v4, v5, v6, v7, c2);
  FA_eight_Rev_2 index7(t0, t1, t2, t3, t4, t5, t6, t7, v4, v5, v6, v7,
       UNCONNECTED_HIER_Z186, UNCONNECTED_HIER_Z187,
       UNCONNECTED_HIER_Z188, c1, y[8], y[9], y[10], y[11], y[12],
       y[13], y[14], y[15], c3);
endmodule

